eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/auth/user