# configuration properties shared by all services,
# which can be overridden by specific service's own configuration
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      # https://github.com/spring-cloud/spring-cloud-netflix/issues/2541
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka} # Spring default behavior, just to be explicit
