# configuration properties shared by all services,
# which can be overridden by specific service's own configuration
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/auth/user

spring:
  security:
    user:
      password: password
