eureka:
  client:
    register-with-eureka: true

spring:
  resources:
    static-locations: "classpath:/static/dist/"
  cloud:
    gateway:
      routes:
      - id: message-service
        uri: lb://message-service
        predicates:
        - Path=/message/**
