spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

  profiles:
     active: native

server:
  port: 8888

spring:
  security:
    user:
      password: password

spring:
  application:
    name: config-server

spring:
  cloud:
    config